config/routes.rb
Rails.application.routes.draw do
  
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	root 'welcome#index'

    resources :sessions
    resources :users do
	      resources :todos
    end
    resources :admin

  	get "/sign_in" => "sessions#new", as: "sign_in"
	  get "/users/new" => "users#new", as: "sign_up"
  	delete "/sign_out" => "sessions#destroy", as: "sign_out"
  	post "/sessions/new" => "sessions#create" 
    delete "/admin/:admin_id/user/:user_id" => "admin#destroy", as: "kill_user"
  	put "/users/:user_id/todos/:id" => "todos#index"
    get 'braintree/new'
    post 'braintree/new'
    post 'braintree/checkout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord

	belongs_to :user
	validates :description, presence: true
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	enum status: [:Incomplete, :Complete]

	
end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password
	has_many :todos, dependent: :destroy
	validates :email, uniqueness: true
	validates :email, :uniqueness=> true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => "error"}
	validates :password, :email, :password_confirmation, presence: true, on: [:create]
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	enum role: [:Noobie, :Whaler, :Admin]
	before_create { generate_token(:auth_token) }

	def self.search_by(search_term)
		where("LOWER(username) LIKE :search_term OR LOWER(email) LIKE :search_term", search_term: "%#{search_term.downcase}%")
	end

	def generate_token(column)
	    begin
	      self[column] = SecureRandom.urlsafe_base64
	    end while User.exists?(column => self[column])
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_action :authorize_admin

	def index
		@admin = current_user
	end

	def show
		@users = User.all
		@user = User.find(params[:id])
		if params[:search]
			@search_term = params[:search]
			@users = @users.search_by(@search_term)
		end
	end

	def destroy
		@user = User.find(params[:user_id])
		if @user.destroy
			redirect_to admin_path(current_user)
		else
			redirect_to admin_path(current_user)
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def signed_in?
       !current_user.nil?
    end

	private

	def current_user
		@current_user ||= User.find_by_auth_token( cookies[:auth_token]) if cookies[:auth_token]
	end
	
	helper_method :current_user

	def authorize_admin
		redirect_to users_path, alert: "GET OUT!!!" if current_user.Noobie? || current_user.Whaler?
	end

	def authorized
		redirect_to users_path, alert: "You are too poor to use this." if current_user.Noobie?
	end

end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  	def new
 	 	@client_token = Braintree::ClientToken.generate
	end

	def checkout
		nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

		result = Braintree::Transaction.sale(
		   	:amount => "10.00", #this is currently hardcoded
		   	:payment_method_nonce => nonce_from_the_client,
		   	:options => {
		     	:submit_for_settlement => true
		    }
		)

		if result.success?
			current_user.Whaler!
		    redirect_to users_path, :flash => { :success => "Thanks for the money!" }
		else
		    redirect_to :root, :flash => { :error => "Are you kidding me? Please get out if you have no money" }
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		if params[:session][:password] == params[:session][:password_confirmation]
			if @user = User.find_by(email: params[:session][:email])
				if @user.authenticate(params[:session][:password])
					if params[:remember_me]
      					cookies.permanent[:auth_token] = @user.auth_token
    				else
      					cookies[:auth_token] = @user.auth_token  
    				end
					redirect_to users_path
				else
					render 'new'
				end
			else
				render 'new'
			end
		else
			render 'new'
		end	

	end


	def destroy
		cookies.delete(:auth_token)
		redirect_to root_path
	end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	before_action :authorized

	def index
		@user = User.find(params[:user_id])
		@todo = Todo.order(:id)
	end

	def new
		@todo = Todo.new
	end

	def create
		@user = User.find(params[:user_id])
		@todo = current_user.todos.new(todo_params)
		if @todo.save
			redirect_to user_todos_path
		else
			render 'new'
		end
	end

	def update
		@todo = Todo.find(params[:id])
		if @todo.update(edit_todo_params)
			redirect_to user_todos_path
		end
	end

	def destroy
		@todo = Todo.find(params[:id])
		if @todo.user_id == current_user.id
			@todo.destroy
			redirect_to user_todos_path
		else
			redirect_to user_todos_path
		end
	end

	private

	def todo_params
		params.require(:todo).permit(:description, :image)	
	end

	def edit_todo_params
		params.permit(:status)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index	
		@user = current_user
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save 
			if @user.id == 1
				@user.Admin!
				cookies[:auth_token] = @user.auth_token
				redirect_to admin_index_path
			else
				cookies[:auth_token] = @user.auth_token
				redirect_to users_path
			end
		else
			render "new"
		end
	end

	def show
		@user = User.find(params[:id])
		if current_user.role != "Admin"	
			if @user.id != current_user.id
				redirect_to users_path
			end
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			if @user.Admin?
				redirect_to admin_index_path
			else
				redirect_to user_path
			end
		else
			render 'edit'
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :username, :avatar)
	end

	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h1>WELCOME BACK MASTER</h1>

<%= link_to "Users' List", admin_path(@admin) %><br>
<%= link_to "Not Todo Page", user_todos_path(@admin) %><br>
<%= link_to "View Profile", user_path(@admin) %><br>
<%= link_to "Sign Out", sign_out_path, method: :delete %>

app/views/admin/show.html.erb
<h2>Users' List</h2>

<%= form_for "",url: admin_path, role: "search", method: :get do %>
	<%= text_field_tag :search, @search_term, placeholder: "Search by Username or Email" %>
	<%= submit_tag "Search" %>
<% end %>


<table>
		<tr>
			<th>No.</th>
			<th>Image</th>
			<th>Username</th>
			<th>Email</th>
			<th>Role</th>
		</tr>
		<% @users.each_with_index do |u,index| %>
			<tr>
				<td><%= index + 1 %>.</td>
				<td>
				<% if u.avatar.present? %>
					<%= image_tag u.avatar.url(:thumb) %>
				<% else %>
					<%= image_tag "UK.jpg", style:"width:100px" %>
				<% end %>
				</td>
				<td><%= u.username %></td>
				<td><%= u.email %></td>
				<td><%= u.role %></td>
				<td><%= link_to "View Profile", user_path(u) %>
				<% if u.role != 'Admin' %>
				<td><%= link_to "Kill User", kill_user_path(admin_id: current_user.id, user_id: u), method: :delete, data: { confirm: "Are you sure?" } %></td>
				<% end %>
			</tr>
		<% end %>
	</table>

<%= link_to "Refresh Users' List", admin_path %><br>
<%= link_to "Back to Admin Page", admin_index_path %>

app/views/braintree/new.html.erb
<h2>Give me the money</h2>

<div class="demo-frame">

  <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>
  <% end %>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

</div>

<script>
var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';
braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }
  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }
    submit.removeAttribute('disabled');
    form.addEventListener('submit', function (event) {
      event.preventDefault();
      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }
        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dumbstuff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h2> The useless stuff that nobody cares that I don't even know why I even make this for app!!!</h2>

<% if @user.todos.count != 0 %>
	<table>
		<tr>
			<th>No.</th>
			<th>Image</th>
			<th>Description</th>
			<th>Status</th>
		</tr>
		<% current_user.todos.each_with_index do |t,index| %>
			<tr>
				<td><%= index + 1 %>.</td>
				<td>
				<% if t.image.present? %>
					<%= image_tag t.image.url(:thumb) %>
				<% else %>
					No image
				<% end %>
				</td>
				<td><%= t.description %></td>
				<td><%= t.status %></td>
				<% if t.Incomplete? %>
				<td><%= button_to "Complete", user_todo_path(@user, t, :status => :Complete ), :method => :put, remote: true,  data: { confirm: "I'm pretty sure you havent done it yet. But whatever, who's looking?" } %>
				<% end %>
				<td><%= link_to "Delete Todo", user_todo_path(@user, t), method: :delete, data: { confirm: "Are you sure?" }, remote: true %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	You have no Todos for now.
<% end %>

<%= link_to "New Todo", new_user_todo_path %><br>
<% if @user.Admin? %>
	<%= link_to "Admin Page", admin_index_path %><br>
<% else %>
	<%= link_to "User Page", users_path %><br>
<% end %>
<%= link_to "Sign Out", sign_out_path, method: :delete %>

app/views/todos/new.html.erb
<h2> Create Your Not Todo </h2>

<%= form_for @todo, url: user_todos_path do |f| %>
	
	<%= f.label :image %>
	<%= f.file_field :image %>
	
	<%= f.label :description %>
	<%= f.text_field :description, placeholder: "Description" %>
	
	<%= f.submit "Add Not Todo" %>


<% end %>

<h4>When you create a Not Todo, a puppy dies. -Nicholas OWH, Mentor of NEXT Academy</h4>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
    
    <h1>Edit</h1>

    <%= f.label :email %>
    <%= f.text_field :email, placeholder: "Email" %><br>  

    <%= f.label :new_password %>
    <%= f.password_field :password, placeholder: "Password" %><br> 

    <%= f.label :new_password_confirmation %>
    <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %><br>

    <%= f.label :avatar %>
  	<%= f.file_field :avatar %><br>

 	<%= f.submit :"Update" %>

<% end %>  

<%= link_to "Back", user_path(current_user) %>

app/views/users/index.html.erb
<h2>Hello <%= @user.username %>

<% if @user.Noobie? %>
	<h4>Why so much effort to create an account and sign in? You don't even know what this site does don't you? This just proves that your IQ is low.</h4>
	<h4>Fine. Since you are so persistant in finding out what this site does, please pay up. Else this is all the site has to offer.</h4>
	<%= button_to "Show me the money", braintree_new_path %><br>
<% elsif @user.Whaler? %>
	<h4>Wow rich kid. Thanks for the money. As promised, here is the <%= link_to "link", user_todos_path(@user) %> to this website's function.</h4><br>
<% elsif @user.Admin? %>
	<h4>Welcome back master. Here to kill more users again?</h4>
	<%= link_to "Admin Page", admin_index_path %><br>
<% end %>


<%= link_to "View Profile", user_path(@user) %><br>
<%= link_to "Sign Out", sign_out_path, method: :delete %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
    <h1>Sign Up</h1>

    <h5>Username is unchangeable. Please take note</h5>
    <%= f.label :username %> 
  	<%= f.text_field :username, placeholder: "Username" %><br>

    <%= f.label :email %>
    <%= f.text_field :email, placeholder: "Email" %><br>

    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "Password" %><br> 

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %><br>

  	<%= f.label :avatar %>
  	<%= f.file_field :avatar %><br>

  	<%= f.submit :"Sign Up" %> 

<% end %>   

<%= link_to "Back", root_path %>

app/views/users/show.html.erb
<h2>Profile Page</h2>

<% if @user.avatar.present? %>
	<%= image_tag @user.avatar.url(:thumb) %>
<% else %>
	<%= image_tag "UK.jpg", style:"width:100px" %>
<% end %>
<h4>Username: <%= @user.username %></h4>
<h4>Email: <%= @user.email %></h4>

<%= link_to "Edit Profile", edit_user_path %><br>
<% if current_user.Admin? %>	
	<%= link_to "Back to Users' List Page", admin_path(current_user) %><br>
	<%= link_to "Back to Admin Page", admin_index_path %>
<% else %>
	<%= link_to "Back", users_path %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to DumbStuff!!</h1>

<h4>By just viewing this page your IQ will drop by 100</h4><br>
<h4>And if you view the codes that forms this webapp, you will probably die of cancer</h4>


<% if current_user %>
	<%= link_to "Sign Out", sign_out_path, method: :delete %>
	<%= link_to "User Page", users_path %>
<% else %>
	<%= link_to "Sign In", sign_in_path %>
	<%= link_to "Sign Up", sign_up_path %>
<% end %>